# Generated by Django 5.2.17 on 2026-09-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0002_tasklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='about',
            new_name='note',
        ),
    ]
