# Generated by Django 5.2.17 on 2026-09-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0004_remove_tasklist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Task',
            field=models.CharField(max_length=100),
        ),
    ]
