# Generated by Django 5.2.17 on 2026-09-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0003_rename_about_tasklist_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
    ]
