# Generated by Django 5.2.17 on 2026-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0005_alter_tasklist_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
