# Generated by Django 5.2.17 on 2026-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodflow', '0006_tasklist_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='animations',
            field=models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('focused', 'Focused'), ('tired', 'Tired'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('excited', 'Excited')], default='happy', max_length=20),
        ),
    ]
